### ISSUE TITLE
Refactor to src layout

### ISSUE THREAD

**Issue by michele-riva** [viperleed/viperleed#226]
I have been running a few tests concerning packaging of `viperleed`.

I have just realized that our current repository layout prevents us from executing `pytest` tests against the *installed* version rather than the *source code*. The reason lies in the fact that we use 'utility modules' in the tests, from which we import stuff. The `--import-mode=importlib` option of `pytest`, which we have set in `pyproject.toml`, does not allow one to do this cleanly, as importlib is not 'recursive' (see https://github.com/pytest-dev/pytest/issues/8964 for details). As a workaround, we do have to set the `pythonpath` config option for `tool.pytest`.

However, the above settings essentially means that we always run tests against the source code. The reason is that our layout:

```
root/
├── ...
├── viperleed/
│   ├── calc/
│   └── ...
├── tests/
│   ├── calc/
│   │   ├── helpers.py
│   │   └── ... 
│   └── ... 
├── pyproject.toml
└── ...
```

has `viperleed` right next to `tests` in the tree. And the `root` folder is added as a `pythonpath` (due to the requirements of our tests mentioned above).

The solution to this issue would be to move the `viperleed` folder above one level down, to `src/viperleed`, i.e., adopting the `src` layout. This is suggested in the pytest [documentation](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html) and most projects actually use it.

I would like to hear @amimre's and @fkraushofer's opinion about this, but I'd be strongly in favor of doing it. It ensures that what we distribute works as expected after installation.

**Comment by amimre** [comment]
Fine with me in principle.
Do we even need the Viperleed subdirectory in that case? Can't we go directly with e.g. src/calc?

**Comment by michele-riva** [comment]
>  Can't we go directly with e.g. src/calc?

I don't think we can. I will test it out, but I believe that the name of that folder (except for the `src` top-level one) is the name with which it will be installed by `pip` in `site-packages`. The `project.name` you give in the `pyproject.toml` is only the one with which it is stored on pypi. This would mean that we'd have

```python
from src import calc
```

instead of

```python
from viperleed import calc
```

**Comment by michele-riva** [comment]
I can confirm that

```
python -m build
```

fails with @amimre's suggestion. Here the traceback for posterity:

```
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools
* Getting build dependencies for sdist...
No `packages` or `py_modules` configuration, performing automatic discovery.
`src-layout` detected -- analysing .\src
discovered packages -- ['calc', 'extensions', 'guilib', 'utilities', 'calc.classes', 'calc.files', 'calc.lib', 'calc.sections', 'calc.classes.rparams', 'calc.classes.slab', 'calc.classes.rparams.special', 'calc.files.parameters', 'extensions.build', 'extensions.interpolation', 'extensions.rfactor', 'extensions.smoothing', 'guilib.fonts', 'guilib.icons', 'guilib.leedsim', 'guilib.icons.src', 'guilib.leedsim.classes', 'guilib.leedsim.exported', 'guilib.leedsim.input examples', 'utilities.beams', 'utilities.poscar']
discovered py_modules -- ['cli', 'cli_base', 'gui', '__init__', '__main__']
Traceback (most recent call last):
  File "C:\Users\miche\OneDrive\Work\Vienna\SPECSLab\Technical\Upgrades\Python LEED-IV\000-git\virtual_environments\distribute_viperleed\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
    main()
  File "C:\Users\miche\OneDrive\Work\Vienna\SPECSLab\Technical\Upgrades\Python LEED-IV\000-git\virtual_environments\distribute_viperleed\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "C:\Users\miche\OneDrive\Work\Vienna\SPECSLab\Technical\Upgrades\Python LEED-IV\000-git\virtual_environments\distribute_viperleed\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 308, in get_requires_for_build_sdist
    return hook(config_settings)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\build_meta.py", line 330, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\_distutils\core.py", line 158, in setup
    dist.parse_config_files()
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\dist.py", line 632, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 70, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 139, in read_configuration
    return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 164, in expand_configuration
    return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 212, in expand
    self._expand_all_dynamic(dist, package_dir)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 257, in _expand_all_dynamic
    version=self._obtain_version(dist, package_dir),
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 306, in _obtain_version
    return _expand.version(self._obtain(dist, "version", package_dir))
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 295, in _obtain
    return self._expand_directive(
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\pyprojecttoml.py", line 289, in _expand_directive
    return _expand.read_attr(directive["attr"], package_dir, root_dir)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\expand.py", line 185, in read_attr
    spec = _find_spec(module_name, path)
  File "C:\Users\miche\AppData\Local\Temp\build-env-efbzgf6g\lib\site-packages\setuptools\config\expand.py", line 200, in _find_spec
    raise ModuleNotFoundError(module_name)
ModuleNotFoundError: viperleed

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist

```

**Comment by michele-riva** [comment]
Perhaps one example in which testing the installed version would be useful.

While packaging I realized that we had forgotten to include non-python files in the repository. Examples: all the Fortran sources of the `extensions`; `_checksums.dat`; font and icon files for the GUI. If we were to run tests on the source repository, we would not realize that these (or, better, other files that we will include in the future) are missing. This may cause unexpected behavior in distributed code, but would not be detected during our testing.

One pro about having a `src` that only contains `viperleed`: `src` will be pretty much transparent on GitHub. It will appear in one line, as `src/viperleed` on the Code page. However, on our (i.e., the developers') filesystem, it will still appear as a folder. End users will se no difference. The will have simply `viperleed` in their `site-packages`.

Testing of the source code can still be done using an editable install. We would not see the difference compared to now.
