### ISSUE TITLE
K thermocouple issues at low T

### ISSUE THREAD

**Issue by iap-ltlab** [viperleed/viperleed#240]
(This is @michele-riva, writing from the LT Lab)

Trying to measure `T ~ -140C` with a K thermocouple gave the following exception:

```
ERROR:root:Traceback (most recent call last):
  File "C:\Users\LTSTM\Documents\viperleed\guilib\measure\controller\viperinocontroller.py", line 619, in on_data_ready
    self.__convert_thermocouple_voltages()
  File "C:\Users\LTSTM\Documents\viperleed\guilib\measure\controller\viperinocontroller.py", line 989, in __convert_thermocouple_voltages
    self.thermocouple.temperature(v, t0)
  File "C:\Users\LTSTM\Documents\viperleed\guilib\measure\classes\thermocouple.py", line 304, in temperature
    raise ValueError(
ValueError: (Corrected) thermocouple voltage -6.070130825042725 outside range of known coefficients (-5.891, 54.886)
```

There may be something wrong with the way we calculate temperatures back from millivolts. The AUX input was set to 2.5V range.

With incorrectly connected contacts, the temperature was incorrectly read as ~150C (consistent with a measurement by a multimeter).

Notice that the K thermocouple is the only one that uses some extra funny coefficients.

**Comment by iap-ltlab** [comment]
I'm adding a bunch of measurements done by Luca over the weekend that may be useful for testing this bug.
[2024-08-01--05 - cryostat warmup.zip](https://github.com/user-attachments/files/16493417/2024-08-01--05.-.cryostat.warmup.zip)

**Comment by FlorianDoerr** [comment]
We checked the electronics and the contacts going from the thermocouple to the PCB were connected incorrectly. While checking the code, I found no obvious mistakes in the thermocouple.py module at first glance besides a corner case when T of cj compensation was 0°C. Note that now the correct voltage is measured on the arduino side after the connection has been flipped.

**Comment by michele-riva** [comment]
@FlorianDoerr: I'm not sure I understand what went really wrong there. If the thermocouple contacts are swapped, the AUX voltage would change sign. This usually means that the measured temperature changes sign (in °C units; plus typically it is off and goes "the wrong way"). This is what I think was tried back then:

> With incorrectly connected contacts, the temperature was incorrectly read as ~150C (consistent with a measurement by a multimeter).

The only situation that would give the error above would be measuring the CJC temperature with the wrong sign. The measurements attached above, however, do not seem to suggest that this was the case (CJC was always around 26-27°C). Perhaps let's discuss in person.
