### ISSUE TITLE
RecursionError with command-less viperleed utilities

### ISSUE THREAD

**Issue by amimre** [viperleed/viperleed#281]
While working on #274, I noticed that there is a RecursionError being raised when calling `viperleed poscar`without further arguments. @michele-riva fixed similar issues with some of the other CLI utilities, so it's proably an easy fix.
Stack trace is below:

```
Traceback (most recent call last):
  File "/Users/alexander/opt/anaconda3/envs/viperleed/bin/viperleed", line 8, in <module>
    sys.exit(ViPErLEEDMain.run_as_script())
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 423, in run_as_script
    exit_code = cli()
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 256, in __call__
    return command(args)
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 256, in __call__
    return command(args)
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 256, in __call__
    return command(args)
  [Previous line repeated 992 more times]
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 250, in __call__
    args = self.parse_cli_args(args)
  File "/Users/alexander/GitHub/viperleed/src/viperleed/cli_base.py", line 529, in parse_cli_args
    if isinstance(args, argparse.Namespace):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by michele-riva** [comment]
Thanks for reporting. I think I know what the problem is. Here: https://github.com/viperleed/viperleed/blob/a1f2deeb639f41b9758aa53c57116523bc4a1cfa/src/viperleed/utilities/poscar/base.py#L34-L50

I override the parent-class `__call__`, which implements the recursion-error-avoiding solution. The fix should be rather simple. I will work on it tomorrow.

**Comment by michele-riva** [comment]
On a second look, that's probably not the problem. I will need to investigate a bit more.
